# Generated by Django 3.1.7 on 2021-06-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210517_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to='profiles'),
        ),
    ]
