# Generated by Django 3.1.7 on 2021-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return_product',
            name='reason',
        ),
    ]
