# Generated by Django 3.1.7 on 2021-07-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210714_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='return_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
