# Generated by Django 3.1.7 on 2021-07-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210714_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return_product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='return_product'),
        ),
        migrations.AlterField(
            model_name='return_product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='return_product'),
        ),
        migrations.AlterField(
            model_name='return_product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='return_product'),
        ),
    ]
