# Generated by Django 3.1.7 on 2021-07-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210715_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='returned_order',
            field=models.BooleanField(default=False),
        ),
    ]
