# Generated by Django 3.1.7 on 2021-07-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210723_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='times',
            field=models.IntegerField(default=1),
        ),
    ]
